### ISSUE TITLE
"cc init" output unclear

### ISSUE THREAD

**Issue by buhtz** [vweevers/hallmark#123]
Please see this output of "cc init".
![image](https://github.com/vweevers/hallmark/assets/11861496/8d5e0146-5e2e-4ed9-ad68-4a0392f3b684)

It is not clear to me what it means.

- Is this debug output?
- Is it important for users? Additional information in this output would help.
- Do you use fancy unicode icons somehow? Seems to be that they do get lost in my SSH shell running in a windows 10 command prompt.
- What does this `1:1-1:1` mean?

If this is linter output:
 - It is unexpected because "cc" is not about linting.
 - I am not able to interpret the output even if assuming this is linter output.

**Comment by vweevers** [comment]
> Is this debug output?

No, linter output.

> Is it important for users?

Yes. I suppose we could add a introductory message like "Please address the following issues".

> Do you use fancy unicode icons somehow?

Yes, it normally looks like this:

<img width="528" alt="image" src="https://github.com/vweevers/hallmark/assets/3055345/5d9de525-ad36-4209-858f-429867613809">


Which is more obvious than the output you're getting, also because each line has a hyperlink. See [`vfile-reporter-shiny`](https://github.com/vweevers/vfile-reporter-shiny). If you can figure out why you're not getting pretty output I'll gladly accept a PR.

> What does this `1:1-1:1` mean?

Line numbers. I didn't manage to implement real line numbers here (where for example, `Release (0.7.4) is empty` would point to the offending line in `CHANGELOG.md`) but it's a general feature of `vfile-reporter-shiny`.

> It is unexpected because "cc" is not about linting.

Hallmark was born as a linter, `cc` was only added later. Today I pretty much only use it for its `cc add` feature but I haven't yet decided what to with the rest. It can't be completely stripped out because generating markdown means having opinions on formatting, and there's also value in validating the changelog, both of which means linting is relevant.

**Comment by buhtz** [comment]
IMHO "cc" and "lint" should be treated as separate commands. From my perspective it is unexpected behavior having linter output when doing "cc".

About the hyperlink in terminal output: Treat a terminal as a terminal and nothing more. No unicode symbols or hyperlinks. Not everyone do use a fancy terminal emu in X/Wayland. My initial screenshot is a windows command prompt, running an ssh client, running tmux, running bahs and in the end your hallmark.

**Comment by buhtz** [comment]
Thank you for being so kind.
