### ISSUE TITLE
Add 'hallmark add' command (or similar)

### ISSUE THREAD

**Issue by ralphtheninja** [vweevers/hallmark#84]
When building up a changelog from scratch for an existing project with already existing history it would be handy to be able to do e.g. `hallmark add x.y.z` which would prepend an empty section just like `hallmark bump` but with the given version number. You could also have `hallmark add patch | minor | major`.

Once the changelog has been built, then you'd start using `hallmark bump` from there.

**Comment by ralphtheninja** [comment]
Maybe even have a `hallmark init` command for getting started on a new changelog? Just a thought and maybe for another issue.

**Comment by vweevers** [comment]
To make this easier I'd first like to do https://github.com/vweevers/hallmark/issues/82 (so that we don't have to compute a diff url for the newly added release) and https://github.com/vweevers/hallmark/issues/81 (to simplify sorting).

I assume that if the version in `hallmark add <version>` is older than what's already in the changelog, we'd want to insert a release after/before the closest existing version. Which can be achieved simply by sorting the releases after injection.

Not sure I fully understand the benefit of `add <version>` over `bump <version>`. What's the main difference? That `add` adds an empty release, while `bump` populates it with commits?

**Comment by vweevers** [comment]
Related, I've been wondering about the scope of hallmark. Is it a linter, or a changelog tool? We could fork hallmark into a separate tool for changelogs (the generated content would still follow the hallmark style, but potentially that could be configurable).

**Comment by ralphtheninja** [comment]
> Not sure I fully understand the benefit of `add <version>` over `bump <version>`. What's the main difference? That `add` adds an empty release, while `bump` populates it with commits?

I was a bit confused there. For some reason I didn't use `bump` while adding new versions (copy pasting empty change groups from another file), but it obviously works fine to get all commits inserted and then remove/tweak them.

Maybe `add` should be `insert` instead? And it could be inserted at any point in the changelog as you suggested (good idea). Does that make sense?

**Comment by ralphtheninja** [comment]
Hmm. There's some issue while doing `hallmark bump` on changelogs back in time. E.g. I want to _add_ a new release to the changelog, but it takes todays date instead of the date for the commit or tag that I'm writing the release for.

**Comment by vweevers** [comment]
Yeah, that's https://github.com/vweevers/remark-changelog/blob/873a75634d061d4e120510e16d2a0268861f1d84/index.js#L168

**Comment by vweevers** [comment]
I like `insert` :). It's more clearly the opposite of adding a new release. Eventually, `bump` and `insert` might just be aliases, but we'll see.

I think both these commands could use a `--no-commits` option so that they generate empty releases if desired.

**Comment by ralphtheninja** [comment]
> I think both these commands could use a `--no-commits` option so that they generate empty releases if desired.

Sounds lovely!

**Comment by vweevers** [comment]
I want to make it a subcommand, for extensibility and to make it clear that it operates on the changelog. And just rename `bump` to `add` because having revisited the code I see no reason for two separate commands. Down the line, we could have the following commands (combined with https://github.com/vweevers/hallmark/issues/85).

Add new minor version or existing version to changelog:

```
hallmark cc add minor
hallmark cc add 4.2.0
```

Create a changelog from scratch, either full, without content or limiting versions:

```
hallmark cc init
hallmark cc init --no-commits
hallmark cc init --from 3.8.6 --to 4.2.0
```

**Comment by vweevers** [comment]
[4.0.0](https://github.com/vweevers/hallmark/releases/tag/v4.0.0)
